---
- name: IPI on Baremetal Installation Playbook
  hosts: localhost
  roles:
  - generate-config

  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy_list }}"
