---
- name: IPI on Baremetal Installation Playbook
  hosts: localhost
  tasks:

  - name: Add Kubeconfig to Ansible User .bashrc
    lineinfile:
      path: "{{ ansible_user_dir }}/.bashrc"
      line: "export KUBECONFIG={{ dir }}/auth/kubeconfig"
    tags: install
  
  - debug:
      msg:
        - "Preparing to deploy the OpenShift cluster."
        - "You can tail the logs at {{ dir }}/.openshift_install.log on {{ groups['provisioner'][0] }} to monitor the progress."
  
  - name: Deploy OpenShift Cluster
    shell: |
      /usr/local/bin/openshift-baremetal-install --dir {{ dir }} --log-level debug create cluster
    async: 5400
    poll: 0
    ignore_errors: yes
    tags: install
